### ISSUE TITLE
Custom PvP system

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#20]
Well, nobody will be surprised, but we need to change the PvP system for our RPG, due to skills but also because, in my opinion, the current PvP system offers not enough strategy. Again, I suggest that we're going to write down ideas so we can discuss them in the meeting.

I already had this idea that it would be cool if people who sneak become partially invisible. This can have a huge impact in forest like environment, especially at night.  A skill can then be created that boosts this invisibility.

**Comment by JeromSar** [comment]
@Hakhaktak After some research, it seems that we have two options for invisibility:

1) Full invisibilty, only the sword can be seen, or
2) Partial (50%) invisibility.

Due to the limitations in Minecraft, these are the only two options.

**Comment by Hakhaktak** [comment]
Hmmm, than we'll have to do it with partial invisibility while sneaking. But I guess only with a skill. (depends on how effective it is)

**Comment by derpfacedirk** [comment]
i say it depends on the enviroment
maybe we can make a passive that allows you to become partially invisible but when in a bush or tall grass you may be able to hide and become fully invissible, this would make pvp a lot more tactical because you can work to lay ambushes
all invisibility possiblities obviously wont work when you're in combat

**Comment by Hakhaktak** [comment]
Since I'm going to make a Wheat texture metadata for tallgrass (or another doubleblock) so people can hide in farms.

**Comment by JeromSar** [comment]
@derpfacedirk @Hakhaktak Those are cool ideas, but using both partial invisibility and full visibility would make the implementation a lot more complex.

**Comment by derpfacedirk** [comment]
@JeromSar  true but this is pvp so is not an feature that will arive during alpha

**Comment by Hakhaktak** [comment]
well it certainly is something we can test in the alpha since we'll need it in the beta :p I think that we should implement it during the alpha so that we can test the capture system, and other stuff that can't be test in the alpha, in the closed beta. Also, I think it's a very cool and unique thing to do.

**Comment by Breesboar** [comment]
There are a lot of other things we could change in the default minecraft PvP system, which are less hard to achieve for @JeromSar and @derpfacedirk. I had some ideas too and maybe these are easier to implement in the Alpha of Goldiriath already. Not just the later versions but also the Alpha must have some quality, since we really need a bigger team and we attract people with original content.

These were my ideas (I'm not sure if they are possible to write in code or easier than @Hakhaktak's idea actually.)

-increase the effect of blocking with a sword from 50% (I thought it was 50%) to 75%.
- a limited amount of strokes / time you are allowed to successfully block.
- remove the damage bonus from jumping while fighting and adding a damage penalty for it, because I think this bonus makes the battles kinda derp and just chaotic.
- Some kind of stamina system in which a full stamina bar results in a higher performance in combat. More nuanced; When someone hits an entity while his stamina bar is completely full, his attack will tend to have a higher chance of doing more damage than low damage (It’ll make the chance bar not linear but rather a bit square rooted graph like). But, when hitting someone, of course the stamina will lower since you’re performing a stamina costing action. A lower stamina then will result in a less square rooted “chance graph” and a more linear “chance graph” (do you get what I mean?). But, if you rest for a while, or just maybe over a few seconds, you will gain stamina. We can say that you must not perform any kind of strokes to regenerate your stamina. This kind of system will prevent strike spamming during battles. (It’s kind of based on the Hide and Seek system of the Hive)

NOTE: This system is far from perfect and we need to think it through a lot of times. Maybe even drawing graphs and stuff too make clear how it should work. Also, blocking should cost stamina, but the staminabar regenerates faster than blocking decreases it. Let us discuss this the next meeting.
- a dodge system, which allows players to quickly move left, right or backwards a few blocks.
- a stunning effect when you hit someone who is blocking. Hitting someone when he is blocking will give the certain attacker a knockback (lvl I) and the hit will cost him twice the stamina as usual.
- backstabbing will result in a more effective attack and therefore more powerful hit.
- special attacks, which will drain more stamina than regular attacks, like a quick step forward whilst giving your opponent a stroke. This can result in more damage, since you “power” your stroke more than usually.

**Comment by derpfacedirk** [comment]
@Breesboar
first i was thinking of making blocking a skill so the effectiveness will be affected by that and you will in fact have a max
I would agree with you on the damage bonus
I really like your third idea here. This will be hard to implement however, not in the way that the code itself will be complicated, just because we have to make a realistic and not to extreme graph for this

dodge system would be cool. however i'm not sure how possible it is within minecraft
the stunning effect could be an upgrade for the skill
I agree here, maybe it will also cost less stamina
these are called skill and will be implemented

**Comment by Hakhaktak** [comment]
I've been thinking with @Breesboar about the stamina and I really want to implement such a system, since it'll prevent people from just spamming with their sword. It'll make combat last longer.

**Comment by derpfacedirk** [comment]
I think the stamina would be a good idea

**Comment by cashenkes** [comment]
Do you guys have a plan for combat? I think that the stamina wil be a good feature, but what kind of combat are we making? Most MMO's i have seen (all) use a skill based pvp system. Basically you use your skills or you get rekt. So we wont really have the problem of ppl just spamming their sword because they would just die.

**Comment by Hakhaktak** [comment]
Nah I'm not for a skill based MMO, I do not prefer that kind of combat because it'll be more hotbar clicking than actual fighting.. I think skills can give special attacks, but those shouldn't give a too big advantage. Also, plz no aoe skills.. :D

**Comment by derpfacedirk** [comment]
@Hakhaktak I disagree. its not just hotbar clicking if done right.
for one you will need to aim skills just like your weapon. and AOE skill are a must.
if you're a mage and you're on your own agains 6 mobs you'll change your mind. trust me
skills should and always will have the power to turn the tide of a battle.
and arguments can be made that without skills its just sword spamming and who clicks faster wins

**Comment by Hakhaktak** [comment]
Then you are only talking about a pvp system in which spam clicking would actually work. I suggest we're not going to use such a system anyway (and of course magic is AoE but that's magic and not a combat skill). I think the combat should be focused on the main pvp with skills around it to make it better. You can't build on a broken skeleton, we need to fix the PvP to make sure you can even play without skills and win without skills, although it'll be quite a bit harder to do so. PvP base system has a priority to skills imo.

**Comment by Breesboar** [comment]
Let's make this clear. There are only two things that determine the course of a fight or battle:
- strategic combat (this allows players to gain real-life skills for a game and get better at it. This makes combat fun and will be one of the reasons people come visit our server again. This kind of combat is more important for the late-game)
- level-based combat (the player with the higher level will have more in-game skills and thereby advantages against the lower level player. Short said: the higher level player wins. This level system's only purpose is keeping people out of zones they're not allowed to enter yet. This kind of combat is more important for the early-game)

We need the good of both worlds to make a good MMO. Making one of them dominant will result to a bad MMO. If we decide not to implement a strategic combat system and leave the regular sword/spell/skill spamming, the level-based combat will become dominant and the fights in our MMO will simply suck, even if the two people fighting have the same level. The in-game skills are not strategic because they're static and unchangeable. That's also why we need an issue about skills.

I agree with Hakhaktak and I think we really need to change the combat system of Minecraft drastically, to make the so important late-game better. I personally don't really care if a level 5 person enters a level 15 zone. He will not be able do quests in that zone and he will not receive experience for slaying mobs in that zone. And I think that if this level 5 player is super MLG pro, he deserves to make a chance against higher level players.

**Comment by derpfacedirk** [comment]
The correct timing of skills in battle is what makes them useful and allow you to turn a battle in your favor.
Additionally, please keep in mind that pvp will most likely not happen until max level.

But, yes we need to change minecraft's combat system.
Just when discussing this remember that not only are we changing how pvp works, but also how PvE works.
This means that some changes that would work in PvP may not be a good idea because they will destroy the basis for PvE.
A tried and true method that (to my knowledge) almost every modern MMO uses is: tiy gave a base atack and skills.
Using your skills you can give yourself and your allies an andvantage or your enemies a disadvantage.

**Comment by Hakhaktak** [comment]
What are those skills we are talking about? Better weapon wielding? Special attacks? I really think we should make a very good basic PvP and do the skills as an "add-on". We are going to keep in mind that PvE shouldn't be destroyed indeed, very good point there, but before we are even thinking of implementing skills I personally think we should "fix" the PvP (and PvE).

**Comment by cashenkes** [comment]
@Hakhaktak 
Can you give an example of how you would want the PvP/PvE to work?
That would help with us figuring out if we can use it.

**Comment by Hakhaktak** [comment]
- Different types of weapons will have a different hits/time ratio. Think of a light sword capable of fast hits but low damage and a axe for slow but devastating hits. Maybe even spears with moddels, if it's possible tho.
- A lower stamina will result in a lower damage, but explained correctly, a high stamina will give you a bonus, a 40% stamina will give normal damage and 0% stamina will give you dramatically low damage output.
- Different types of weapons will have a different stamina
- A dodge effect, maybe by triple (or just double) tapping the "A" and/or "D" button, depending which key refers to "walk left" and "walk right".
- Certain types of weapons will be effective against certain types of armor. 

These things will make the PvP not like a chaotic bloodbath were everybody jumps inside, but instead let people rethink their strategy. When having both a sword and an axe and you see someone in heavy armor, you'll be crazy to charge on him with a sword. Since he will have nearly the same attack speed (due to his armor) you are a fair match for him, although you have light armor. 

These features will balance PvP more and create more options. In stead of Armor v Armor, someone now can choose to go light armor instead with a heavy axe. He then will be more "open" to arrow fire, but at least he got a better walking speed, something the heavy armor lads don't have. It provides the player with more possible combat combinations. A important thing tho, we must balance this extremely good by testing it with a closed community to prevent people from creating OP combinations.

**Comment by Hakhaktak** [comment]
Did I make myself clear?

**Comment by cashenkes** [comment]
@Hakhaktak 
I more or less meant an example from another game. So I can kindof see how it works. Because I can kindof make the picture, but I do hope it works better then that...

Also on a side note; I do not think we can have a dodge effect by letting players double tab their movement keys, and PvP/PvE needs to be ballanced either way. 

On a side side note: Different weapons will have different stamina .... cost or amount? (As in cost more or less stamine, or give you more or less stamina)

**Comment by Hakhaktak** [comment]
Skyrim and the Stamina system, Witcher and the Dodge system, War of the Roses for the different types of weapons and their combat speed. 

Indeed a dodge system may be a hard thing to achieve and can be buggy, but at least we can try it.

Different weapons will COST different amounts of stamina. A sword will cost less than a axe, but less than a club. Bows will cost not much stamina, but when fully stretched it will drain stamina. Also, it would be cool if the accuracy will decrease the longer you keep the bow fully stretched. (this is from War of the Roses and it works really good, making sure archers can't camp in a corner)

**Comment by derpfacedirk** [comment]
@Hakhaktak Are you aware that all of the games you talk about, except for war of the roses, are single player only?
Some of these mechanics are amazing in single player or co-op games, but in MMOs they may not work as well.

**Comment by cashenkes** [comment]
I do not think that those games are the games to base an MMO PvP system around.

**Comment by Hakhaktak** [comment]
Stamina is not only in skyrim tho. Dodging is imo something that's also good in a MMO. Aoe attacks are not funny and too easy, so I rather prefer not to seenthat. Ofc splash potions will have an aoe but thats the whole idea. I honestly, again, don't want magic.

**Comment by cashenkes** [comment]
Stamina is in a lot of games, but there is not 1 way to use stamina.
Dodging is good in an MMO, but what do we have that needs dodging?
'Aoe attacks are to easy' what does that mean?
And splash potions are fine, but no magic?

**Comment by Hakhaktak** [comment]
Aoe attacks bring less tactics in the game. One now does simply walk in mordor and does an aoe attack.

Splash potions need to be made, and are quite hard to composite since you'll need some special ingredients. The potion then is extremely powerful and a very handy weapon to have. If magic is implemented the potions would be kind of useless. I prefer potions above magic.

**Comment by Hakhaktak** [comment]
And indeed stamina is in a lot of games, and I think it's a must. But we really need to balance the hell out of it.

**Comment by cashenkes** [comment]
Aoe attacks do not necessarily bring less tactics into the game, why would the enemy even let you get that close in the first place? You need skill to get close enough that you can hit your Aoe and the enemy cant hit theirs.

So I do not really get your point of Aoe's bringing less tactic into the game.
