### ISSUE TITLE
Questing 101

### ISSUE THREAD

**Issue by zhhussain** [derpfacedirk/Goldiriath#48]
**moved to https://github.com/Goldiriath/Quests/issues/2**

**Comment by Haidarz2G** [comment]
If anything seems odd or if you don't quite seem to understand something, feel free to object or ask something

**Comment by cashenkes** [comment]
I do have a small question. Do you think it would be wise for us to label every quest? We could for example add a ''type'' to all the quests that are posted on the wiki page.
Other then that it looks great. And I really like your idea for Nemesis type quest, since its something I hadn't really thought about.
